name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: 
              npm install cypress --save-dev
              npm i -D @shelex/cypress-allure-plugin
              npm install --save-dev mocha-allure-reporter allure-commandline
          start: 
              npx cypress run --record --key 730f5e89-2807-4f18-979f-202508fb31e1 --parallel
